version: '3.8'

services:
  dev:
    container_name: shermaniac-dnd-helper-express-dev
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - INNER_PORT = ${INNER_PORT}
        - OUTER_PORT = ${OUTER_PORT}
    ports:
      - ${OUTER_PORT}:${INNER_PORT}
    env_file:
      - .env
    volumes:
      - ./:/usr/app
      - ignore:/usr/app/node_modules
volumes:
  ignore: